"""Starter word list seeded on first run (only when the word list is empty),
so there's something sensible to start from instead of an empty table.
Fully editable/removable afterward via the Word List page.
"""

from app.domain import Severity

DEFAULT_WORDLIST: list[tuple[str, Severity]] = [
    # child / scatological -- muted only on the Child track (Teen track lets these through)
    ("butt", Severity.child),
    ("poop", Severity.child),
    ("crap", Severity.child),
    ("fart", Severity.child),
    ("freaking", Severity.child),
    ("dang", Severity.child),
    ("screw", Severity.child),
    ("sucks", Severity.child),
    ("douche", Severity.child),
    ("badass", Severity.child),
    ("douchebag", Severity.child),
    ("douchey", Severity.child),
    ("frickin", Severity.child),
    ("frigging", Severity.child),
    ("crappy", Severity.child),
    # teen -- muted on both the Child and Teen tracks (old moderate + strong profanity)
    ("ass", Severity.teen),
    ("asshole", Severity.teen),
    ("bastard", Severity.teen),
    ("bitch", Severity.teen),
    ("bullshit", Severity.teen),
    ("damn", Severity.teen),
    ("goddamn", Severity.teen),
    ("hell", Severity.teen),
    ("dick", Severity.teen),
    ("piss", Severity.teen),
    ("prick", Severity.teen),
    ("whore", Severity.teen),
    ("slut", Severity.teen),
    ("shit", Severity.teen),
    ("fuck", Severity.teen),
    ("fucking", Severity.teen),
    ("fucked", Severity.teen),
    ("motherfucker", Severity.teen),
    ("cunt", Severity.teen),
    ("cocksucker", Severity.teen),
    # compounds/inflections of the roots above that whole-word matching on the
    # root alone can't catch (see app/subtitles/matcher.py -- \bfuck\b doesn't
    # match inside "fucker") -- kept as explicit whole-word entries rather than
    # switching short/common roots like ass/dick/hell/cunt to substring
    # matching, which would false-positive on ordinary words ("class",
    # "addict", "discount").
    ("fucker", Severity.teen),
    ("fuckface", Severity.teen),
    ("fuckin", Severity.teen),
    ("fucktard", Severity.teen),
    ("fuckwit", Severity.teen),
    ("fuckhead", Severity.teen),
    ("fuckup", Severity.teen),
    ("clusterfuck", Severity.teen),
    ("shithead", Severity.teen),
    ("shitface", Severity.teen),
    ("shitty", Severity.teen),
    ("shitstorm", Severity.teen),
    ("dipshit", Severity.teen),
    ("batshit", Severity.teen),
    ("jackass", Severity.teen),
    ("dumbass", Severity.teen),
    ("fatass", Severity.teen),
    ("kickass", Severity.teen),
    ("smartass", Severity.teen),
    ("asswipe", Severity.teen),
    ("assface", Severity.teen),
    ("asshat", Severity.teen),
    ("dickhead", Severity.teen),
    ("dickwad", Severity.teen),
    ("dickface", Severity.teen),
    ("bitchy", Severity.teen),
    ("bitching", Severity.teen),
    ("sonofabitch", Severity.teen),
    ("dammit", Severity.teen),
    ("goddammit", Severity.teen),
    ("twat", Severity.teen),
    ("wanker", Severity.teen),
    ("bollocks", Severity.teen),
    ("arse", Severity.teen),
    ("arsehole", Severity.teen),
    ("skank", Severity.teen),
    ("horseshit", Severity.teen),
    ("nutsack", Severity.teen),
    ("pissed", Severity.teen),
    ("pissy", Severity.teen),
]
